# Generated by Django 3.2.4 on 2021-07-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='laundry',
            table='laundry',
        ),
    ]
