# Generated by Django 3.2.4 on 2021-07-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_delete_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='laundry_address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laundry',
            name='laundry_road',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laundry',
            name='laundry_tel',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
