# Generated by Django 3.2.4 on 2021-07-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('user_pw', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('user_nick', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_phone', models.CharField(max_length=20, unique=True)),
                ('user_lat', models.FloatField(null=True)),
                ('user_lng', models.FloatField(null=True)),
                ('isEmailAlert', models.BooleanField(default=True)),
                ('isPhoneAlert', models.BooleanField(default=True)),
                ('isTempPW', models.BooleanField(default=False)),
            ],
        ),
    ]
