# Generated by Django 3.2.4 on 2021-07-01 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(max_length=20)),
                ('validate_dt', models.DateField()),
                ('card_holder', models.CharField(max_length=20)),
                ('card_pw', models.CharField(max_length=20)),
                ('card_cvc', models.CharField(max_length=5)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
