# Generated by Django 3.2.4 on 2021-07-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_bookmark_reviews'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
