# Generated by Django 3.2.4 on 2021-07-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='content',
            new_name='review_content',
        ),
    ]
