# Generated by Django 3.2.4 on 2021-07-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_content_reviews_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
